<h1 align="center">Hi ðŸ‘‹, I'm Tran Ngoc Tam</h1>

---

# Latest Blog Posts 
<!-- BLOG-POST-LIST:START -->
- [3D Printing Nerd: YOU can make this!!!](https://dev.to/maker_youtube/3d-printing-nerd-you-can-make-this-36g)
- [Adam Savage&#39;s Tested: This Retro Spaceship Model Has Insane Interior Detail!](https://dev.to/maker_youtube/adam-savages-tested-this-retro-spaceship-model-has-insane-interior-detail-4i6)
- [KEXP: Deep Sea Diver - Full Performance &lpar;Live on KEXP&rpar;](https://dev.to/music_youtube/kexp-deep-sea-diver-full-performance-live-on-kexp-50n)
- [Rick Shiels Golf: TEAM UK vs TEAM USA for $250,000 | The Duels: UK Edition](https://dev.to/youtube_golf/rick-shiels-golf-team-uk-vs-team-usa-for-250000-the-duels-uk-edition-4215)
- [IGN: Haikyu!! Fly High! - Official Launch Trailer](https://dev.to/gg_news/ign-haikyu-fly-high-official-launch-trailer-5fih)
<!-- BLOG-POST-LIST:END -->

---

# Latest stack oveflow activity
<table>
  <tr><th>Title</th><th>Link</th></tr>
  <!-- STACKOVERFLOW:START --><tr><td>getting &quot;Fatal error: Cannot declare class phpbb\di\pass\collection_pass, because the name is already in use&quot; by instaling phpbb3 on website</td><td>https://stackoverflow.com/questions/79722722/getting-fatal-error-cannot-declare-class-phpbb-di-pass-collection-pass-becaus</td></tr><tr><td>How to handle a external service timeout with php fpm in web app</td><td>https://stackoverflow.com/questions/79722576/how-to-handle-a-external-service-timeout-with-php-fpm-in-web-app</td></tr><tr><td>Forge CLI: Logged in successfully, but all commands return Your API Token is invalid</td><td>https://stackoverflow.com/questions/79722535/forge-cli-logged-in-successfully-but-all-commands-return-your-api-token-is-inv</td></tr><tr><td>Uncaught &lpar;in promise&rpar; TypeError: NetworkError when attempting to fetch resource in Laravel 12 + Livewire V3 + Vite setup</td><td>https://stackoverflow.com/questions/79722462/uncaught-in-promise-typeerror-networkerror-when-attempting-to-fetch-resource</td></tr><tr><td>Script in Python CVE-2025-49113 Not receiving the connection</td><td>https://stackoverflow.com/questions/79722326/script-in-python-cve-2025-49113-not-receiving-the-connection</td></tr><!-- STACKOVERFLOW:END -->
</table>

---


