<h1 align="center">Hi ðŸ‘‹, I'm Tran Ngoc Tam</h1>

---

# Latest Blog Posts 
<!-- BLOG-POST-LIST:START -->
- [Crea y Elimina Cientos de Clases de Google Classroom con un Script](https://dev.to/elprotectorado/crea-y-elimina-cientos-de-clases-de-google-classroom-con-un-script-5ddj)
- [What is Software Developer? - I](https://dev.to/oliver_butler_a52c1be144d/what-is-software-developer-i-40lc)
- [Creating Materialized View with FAST REFRESH](https://dev.to/mrcaption49/creating-materialized-view-with-fast-refresh-4e8p)
- [IGN: Aggelos 2 - Official Publisher Announcement Trailer](https://dev.to/gg_news/ign-aggelos-2-official-publisher-announcement-trailer-563c)
- [When &quot;Private&quot; Isnâ€™t: The Security Risks of GPT Chats Leaking to Search Engines](https://dev.to/snyk/when-private-isnt-the-security-risks-of-gpt-chats-leaking-to-search-engines-443k)
<!-- BLOG-POST-LIST:END -->

---

# Latest stack oveflow activity
<table>
  <tr><th>Title</th><th>Link</th></tr>
  <!-- STACKOVERFLOW:START --><tr><td>getting &quot;Fatal error: Cannot declare class phpbb\di\pass\collection_pass, because the name is already in use&quot; by instaling phpbb3 on website</td><td>https://stackoverflow.com/questions/79722722/getting-fatal-error-cannot-declare-class-phpbb-di-pass-collection-pass-becaus</td></tr><tr><td>How to handle a external service timeout with php fpm in web app [closed]</td><td>https://stackoverflow.com/questions/79722576/how-to-handle-a-external-service-timeout-with-php-fpm-in-web-app</td></tr><tr><td>Forge CLI: Logged in successfully, but all commands return Your API Token is invalid</td><td>https://stackoverflow.com/questions/79722535/forge-cli-logged-in-successfully-but-all-commands-return-your-api-token-is-inv</td></tr><tr><td>Uncaught &lpar;in promise&rpar; TypeError: NetworkError when attempting to fetch resource in Laravel 12 + Livewire V3 + Vite setup</td><td>https://stackoverflow.com/questions/79722462/uncaught-in-promise-typeerror-networkerror-when-attempting-to-fetch-resource</td></tr><tr><td>Script in Python CVE-2025-49113 Not receiving the connection</td><td>https://stackoverflow.com/questions/79722326/script-in-python-cve-2025-49113-not-receiving-the-connection</td></tr><!-- STACKOVERFLOW:END -->
</table>

---


